// <auto-generated />
// Generated by Tools/generate_nodes.rb from Vendor/prism/config.yml (prism v1.8.1).
// Per-node deserialization (serialize.rb load_node). Re-run: ruby Tools/generate_nodes.rb
#nullable enable

namespace SuperIronRuby.Parser;

public sealed partial class Loader
{
    // serialize.rb load_node: read the type byte, node_id and location, then
    // dispatch on type. Each node reads its flags (varuint) then its fields in
    // declaration order. C# evaluates constructor arguments left-to-right, which
    // matches the serialized field order.
    private Node LoadNode()
    {
        byte type = ReadByte();
        uint nodeId = (uint)LoadVarUInt();
        Location location = LoadLocation();
        switch (type)
        {
            case 1: return new AliasGlobalVariableNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadNode(), LoadLocation());
            case 2: return new AliasMethodNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadNode(), LoadLocation());
            case 3: return new AlternationPatternNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadNode(), LoadLocation());
            case 4: return new AndNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadNode(), LoadLocation());
            case 5: return new ArgumentsNode(nodeId, location, (int)LoadVarUInt(), LoadNodeArray());
            case 6: return new ArrayNode(nodeId, location, (int)LoadVarUInt(), LoadNodeArray(), LoadOptionalLocation(), LoadOptionalLocation());
            case 7: return new ArrayPatternNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadNodeArray(), LoadOptionalNode(), LoadNodeArray(), LoadOptionalLocation(), LoadOptionalLocation());
            case 8: return new AssocNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadNode(), LoadOptionalLocation());
            case 9: return new AssocSplatNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadLocation());
            case 10: return new BackReferenceReadNode(nodeId, location, (int)LoadVarUInt(), LoadConstant());
            case 11: return new BeginNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalLocation(), LoadOptionalNode(), LoadOptionalNode(), LoadOptionalNode(), LoadOptionalNode(), LoadOptionalLocation());
            case 12: return new BlockArgumentNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadLocation());
            case 13: return new BlockLocalVariableNode(nodeId, location, (int)LoadVarUInt(), LoadConstant());
            case 14: return new BlockNode(nodeId, location, (int)LoadVarUInt(), LoadConstantArray(), LoadOptionalNode(), LoadOptionalNode(), LoadLocation(), LoadLocation());
            case 15: return new BlockParameterNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalConstant(), LoadOptionalLocation(), LoadLocation());
            case 16: return new BlockParametersNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadNodeArray(), LoadOptionalLocation(), LoadOptionalLocation());
            case 17: return new BreakNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadLocation());
            case 18: return new CallAndWriteNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadOptionalLocation(), LoadOptionalLocation(), LoadConstant(), LoadConstant(), LoadLocation(), LoadNode());
            case 19: return new CallNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadOptionalLocation(), LoadConstant(), LoadOptionalLocation(), LoadOptionalLocation(), LoadOptionalNode(), LoadOptionalLocation(), LoadOptionalLocation(), LoadOptionalNode());
            case 20: return new CallOperatorWriteNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadOptionalLocation(), LoadOptionalLocation(), LoadConstant(), LoadConstant(), LoadConstant(), LoadLocation(), LoadNode());
            case 21: return new CallOrWriteNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadOptionalLocation(), LoadOptionalLocation(), LoadConstant(), LoadConstant(), LoadLocation(), LoadNode());
            case 22: return new CallTargetNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadLocation(), LoadConstant(), LoadLocation());
            case 23: return new CapturePatternNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadNode(), LoadLocation());
            case 24: return new CaseMatchNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadNodeArray(), LoadOptionalNode(), LoadLocation(), LoadLocation());
            case 25: return new CaseNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadNodeArray(), LoadOptionalNode(), LoadLocation(), LoadLocation());
            case 26: return new ClassNode(nodeId, location, (int)LoadVarUInt(), LoadConstantArray(), LoadLocation(), LoadNode(), LoadOptionalLocation(), LoadOptionalNode(), LoadOptionalNode(), LoadLocation(), LoadConstant());
            case 27: return new ClassVariableAndWriteNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadLocation(), LoadNode());
            case 28: return new ClassVariableOperatorWriteNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadLocation(), LoadNode(), LoadConstant());
            case 29: return new ClassVariableOrWriteNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadLocation(), LoadNode());
            case 30: return new ClassVariableReadNode(nodeId, location, (int)LoadVarUInt(), LoadConstant());
            case 31: return new ClassVariableTargetNode(nodeId, location, (int)LoadVarUInt(), LoadConstant());
            case 32: return new ClassVariableWriteNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadNode(), LoadLocation());
            case 33: return new ConstantAndWriteNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadLocation(), LoadNode());
            case 34: return new ConstantOperatorWriteNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadLocation(), LoadNode(), LoadConstant());
            case 35: return new ConstantOrWriteNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadLocation(), LoadNode());
            case 36: return new ConstantPathAndWriteNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadLocation(), LoadNode());
            case 37: return new ConstantPathNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadOptionalConstant(), LoadLocation(), LoadLocation());
            case 38: return new ConstantPathOperatorWriteNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadLocation(), LoadNode(), LoadConstant());
            case 39: return new ConstantPathOrWriteNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadLocation(), LoadNode());
            case 40: return new ConstantPathTargetNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadOptionalConstant(), LoadLocation(), LoadLocation());
            case 41: return new ConstantPathWriteNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadLocation(), LoadNode());
            case 42: return new ConstantReadNode(nodeId, location, (int)LoadVarUInt(), LoadConstant());
            case 43: return new ConstantTargetNode(nodeId, location, (int)LoadVarUInt(), LoadConstant());
            case 44: return new ConstantWriteNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadNode(), LoadLocation());
            case 45: { LoadUInt32(); return new DefNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadOptionalNode(), LoadOptionalNode(), LoadOptionalNode(), LoadConstantArray(), LoadLocation(), LoadOptionalLocation(), LoadOptionalLocation(), LoadOptionalLocation(), LoadOptionalLocation(), LoadOptionalLocation()); }
            case 46: return new DefinedNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalLocation(), LoadNode(), LoadOptionalLocation(), LoadLocation());
            case 47: return new ElseNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadOptionalNode(), LoadOptionalLocation());
            case 48: return new EmbeddedStatementsNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadOptionalNode(), LoadLocation());
            case 49: return new EmbeddedVariableNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadNode());
            case 50: return new EnsureNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadOptionalNode(), LoadLocation());
            case 51: return new FalseNode(nodeId, location, (int)LoadVarUInt());
            case 52: return new FindPatternNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadNode(), LoadNodeArray(), LoadNode(), LoadOptionalLocation(), LoadOptionalLocation());
            case 53: return new FlipFlopNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadOptionalNode(), LoadLocation());
            case 54: return new FloatNode(nodeId, location, (int)LoadVarUInt(), LoadDouble());
            case 55: return new ForNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadNode(), LoadOptionalNode(), LoadLocation(), LoadLocation(), LoadOptionalLocation(), LoadLocation());
            case 56: return new ForwardingArgumentsNode(nodeId, location, (int)LoadVarUInt());
            case 57: return new ForwardingParameterNode(nodeId, location, (int)LoadVarUInt());
            case 58: return new ForwardingSuperNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode());
            case 59: return new GlobalVariableAndWriteNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadLocation(), LoadNode());
            case 60: return new GlobalVariableOperatorWriteNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadLocation(), LoadNode(), LoadConstant());
            case 61: return new GlobalVariableOrWriteNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadLocation(), LoadNode());
            case 62: return new GlobalVariableReadNode(nodeId, location, (int)LoadVarUInt(), LoadConstant());
            case 63: return new GlobalVariableTargetNode(nodeId, location, (int)LoadVarUInt(), LoadConstant());
            case 64: return new GlobalVariableWriteNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadNode(), LoadLocation());
            case 65: return new HashNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadNodeArray(), LoadLocation());
            case 66: return new HashPatternNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadNodeArray(), LoadOptionalNode(), LoadOptionalLocation(), LoadOptionalLocation());
            case 67: return new IfNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalLocation(), LoadNode(), LoadOptionalLocation(), LoadOptionalNode(), LoadOptionalNode(), LoadOptionalLocation());
            case 68: return new ImaginaryNode(nodeId, location, (int)LoadVarUInt(), LoadNode());
            case 69: return new ImplicitNode(nodeId, location, (int)LoadVarUInt(), LoadNode());
            case 70: return new ImplicitRestNode(nodeId, location, (int)LoadVarUInt());
            case 71: return new InNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadOptionalNode(), LoadLocation(), LoadOptionalLocation());
            case 72: return new IndexAndWriteNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadOptionalLocation(), LoadLocation(), LoadOptionalNode(), LoadLocation(), LoadOptionalNode(), LoadLocation(), LoadNode());
            case 73: return new IndexOperatorWriteNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadOptionalLocation(), LoadLocation(), LoadOptionalNode(), LoadLocation(), LoadOptionalNode(), LoadConstant(), LoadLocation(), LoadNode());
            case 74: return new IndexOrWriteNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadOptionalLocation(), LoadLocation(), LoadOptionalNode(), LoadLocation(), LoadOptionalNode(), LoadLocation(), LoadNode());
            case 75: return new IndexTargetNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadLocation(), LoadOptionalNode(), LoadLocation(), LoadOptionalNode());
            case 76: return new InstanceVariableAndWriteNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadLocation(), LoadNode());
            case 77: return new InstanceVariableOperatorWriteNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadLocation(), LoadNode(), LoadConstant());
            case 78: return new InstanceVariableOrWriteNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadLocation(), LoadNode());
            case 79: return new InstanceVariableReadNode(nodeId, location, (int)LoadVarUInt(), LoadConstant());
            case 80: return new InstanceVariableTargetNode(nodeId, location, (int)LoadVarUInt(), LoadConstant());
            case 81: return new InstanceVariableWriteNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadNode(), LoadLocation());
            case 82: return new IntegerNode(nodeId, location, (int)LoadVarUInt(), LoadInteger());
            case 83: return new InterpolatedMatchLastLineNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadNodeArray(), LoadLocation());
            case 84: return new InterpolatedRegularExpressionNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadNodeArray(), LoadLocation());
            case 85: return new InterpolatedStringNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalLocation(), LoadNodeArray(), LoadOptionalLocation());
            case 86: return new InterpolatedSymbolNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalLocation(), LoadNodeArray(), LoadOptionalLocation());
            case 87: return new InterpolatedXStringNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadNodeArray(), LoadLocation());
            case 88: return new ItLocalVariableReadNode(nodeId, location, (int)LoadVarUInt());
            case 89: return new ItParametersNode(nodeId, location, (int)LoadVarUInt());
            case 90: return new KeywordHashNode(nodeId, location, (int)LoadVarUInt(), LoadNodeArray());
            case 91: return new KeywordRestParameterNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalConstant(), LoadOptionalLocation(), LoadLocation());
            case 92: return new LambdaNode(nodeId, location, (int)LoadVarUInt(), LoadConstantArray(), LoadLocation(), LoadLocation(), LoadLocation(), LoadOptionalNode(), LoadOptionalNode());
            case 93: return new LocalVariableAndWriteNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadLocation(), LoadNode(), LoadConstant(), (int)LoadVarUInt());
            case 94: return new LocalVariableOperatorWriteNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadLocation(), LoadNode(), LoadConstant(), LoadConstant(), (int)LoadVarUInt());
            case 95: return new LocalVariableOrWriteNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadLocation(), LoadNode(), LoadConstant(), (int)LoadVarUInt());
            case 96: return new LocalVariableReadNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), (int)LoadVarUInt());
            case 97: return new LocalVariableTargetNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), (int)LoadVarUInt());
            case 98: return new LocalVariableWriteNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), (int)LoadVarUInt(), LoadLocation(), LoadNode(), LoadLocation());
            case 99: return new MatchLastLineNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadLocation(), LoadLocation(), LoadString());
            case 100: return new MatchPredicateNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadNode(), LoadLocation());
            case 101: return new MatchRequiredNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadNode(), LoadLocation());
            case 102: return new MatchWriteNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadNodeArray());
            case 103: return new MissingNode(nodeId, location, (int)LoadVarUInt());
            case 104: return new ModuleNode(nodeId, location, (int)LoadVarUInt(), LoadConstantArray(), LoadLocation(), LoadNode(), LoadOptionalNode(), LoadLocation(), LoadConstant());
            case 105: return new MultiTargetNode(nodeId, location, (int)LoadVarUInt(), LoadNodeArray(), LoadOptionalNode(), LoadNodeArray(), LoadOptionalLocation(), LoadOptionalLocation());
            case 106: return new MultiWriteNode(nodeId, location, (int)LoadVarUInt(), LoadNodeArray(), LoadOptionalNode(), LoadNodeArray(), LoadOptionalLocation(), LoadOptionalLocation(), LoadLocation(), LoadNode());
            case 107: return new NextNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadLocation());
            case 108: return new NilNode(nodeId, location, (int)LoadVarUInt());
            case 109: return new NoKeywordsParameterNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadLocation());
            case 110: return new NumberedParametersNode(nodeId, location, (int)LoadVarUInt(), (int)ReadByte());
            case 111: return new NumberedReferenceReadNode(nodeId, location, (int)LoadVarUInt(), (int)LoadVarUInt());
            case 112: return new OptionalKeywordParameterNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadNode());
            case 113: return new OptionalParameterNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation(), LoadLocation(), LoadNode());
            case 114: return new OrNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadNode(), LoadLocation());
            case 115: return new ParametersNode(nodeId, location, (int)LoadVarUInt(), LoadNodeArray(), LoadNodeArray(), LoadOptionalNode(), LoadNodeArray(), LoadNodeArray(), LoadOptionalNode(), LoadOptionalNode());
            case 116: return new ParenthesesNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadLocation(), LoadLocation());
            case 117: return new PinnedExpressionNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadLocation(), LoadLocation(), LoadLocation());
            case 118: return new PinnedVariableNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadLocation());
            case 119: return new PostExecutionNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadLocation(), LoadLocation(), LoadLocation());
            case 120: return new PreExecutionNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadLocation(), LoadLocation(), LoadLocation());
            case 121: return new ProgramNode(nodeId, location, (int)LoadVarUInt(), LoadConstantArray(), LoadNode());
            case 122: return new RangeNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalNode(), LoadOptionalNode(), LoadLocation());
            case 123: return new RationalNode(nodeId, location, (int)LoadVarUInt(), LoadInteger(), LoadInteger());
            case 124: return new RedoNode(nodeId, location, (int)LoadVarUInt());
            case 125: return new RegularExpressionNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadLocation(), LoadLocation(), LoadString());
            case 126: return new RequiredKeywordParameterNode(nodeId, location, (int)LoadVarUInt(), LoadConstant(), LoadLocation());
            case 127: return new RequiredParameterNode(nodeId, location, (int)LoadVarUInt(), LoadConstant());
            case 128: return new RescueModifierNode(nodeId, location, (int)LoadVarUInt(), LoadNode(), LoadLocation(), LoadNode());
            case 129: return new RescueNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadNodeArray(), LoadOptionalLocation(), LoadOptionalNode(), LoadOptionalLocation(), LoadOptionalNode(), LoadOptionalNode());
            case 130: return new RestParameterNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalConstant(), LoadOptionalLocation(), LoadLocation());
            case 131: return new RetryNode(nodeId, location, (int)LoadVarUInt());
            case 132: return new ReturnNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadOptionalNode());
            case 133: return new SelfNode(nodeId, location, (int)LoadVarUInt());
            case 134: return new ShareableConstantNode(nodeId, location, (int)LoadVarUInt(), LoadNode());
            case 135: return new SingletonClassNode(nodeId, location, (int)LoadVarUInt(), LoadConstantArray(), LoadLocation(), LoadLocation(), LoadNode(), LoadOptionalNode(), LoadLocation());
            case 136: return new SourceEncodingNode(nodeId, location, (int)LoadVarUInt());
            case 137: return new SourceFileNode(nodeId, location, (int)LoadVarUInt(), LoadString());
            case 138: return new SourceLineNode(nodeId, location, (int)LoadVarUInt());
            case 139: return new SplatNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadOptionalNode());
            case 140: return new StatementsNode(nodeId, location, (int)LoadVarUInt(), LoadNodeArray());
            case 141: return new StringNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalLocation(), LoadLocation(), LoadOptionalLocation(), LoadString());
            case 142: return new SuperNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadOptionalLocation(), LoadOptionalNode(), LoadOptionalLocation(), LoadOptionalNode());
            case 143: return new SymbolNode(nodeId, location, (int)LoadVarUInt(), LoadOptionalLocation(), LoadOptionalLocation(), LoadOptionalLocation(), LoadString());
            case 144: return new TrueNode(nodeId, location, (int)LoadVarUInt());
            case 145: return new UndefNode(nodeId, location, (int)LoadVarUInt(), LoadNodeArray(), LoadLocation());
            case 146: return new UnlessNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadNode(), LoadOptionalLocation(), LoadOptionalNode(), LoadOptionalNode(), LoadOptionalLocation());
            case 147: return new UntilNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadOptionalLocation(), LoadOptionalLocation(), LoadNode(), LoadOptionalNode());
            case 148: return new WhenNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadNodeArray(), LoadOptionalLocation(), LoadOptionalNode());
            case 149: return new WhileNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadOptionalLocation(), LoadOptionalLocation(), LoadNode(), LoadOptionalNode());
            case 150: return new XStringNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadLocation(), LoadLocation(), LoadString());
            case 151: return new YieldNode(nodeId, location, (int)LoadVarUInt(), LoadLocation(), LoadOptionalLocation(), LoadOptionalNode(), LoadOptionalLocation());
            default:
                throw new System.InvalidOperationException($"unknown Prism node type {type}");
        }
    }
}
