using System.Numerics;
using System.Text;
using SuperIronRuby.Parser;

namespace SuperIronRuby.Tests.Parser;

// End-to-end deserialization of real Prism.dump output (fixtures generated by
// Tools/make_testdata.sh from ruby 4.0.2). Proves the generated per-node loader
// (Loader.g.cs) + primitives reconstruct the AST correctly.
public class LoaderSmokeTests
{
    private static (ProgramNode root, Loader loader) Load(string fixture, string source)
    {
        var dir = Path.Combine(AppContext.BaseDirectory, "TestData");
        var serialized = File.ReadAllBytes(Path.Combine(dir, fixture + ".bin"));
        var loader = new Loader(serialized, Encoding.UTF8.GetBytes(source));
        return (loader.LoadProgram(), loader);
    }

    private static StatementsNode Body(ProgramNode p) => (StatementsNode)p.Statements;

    [Fact]
    public void Add_IsCallNodeWithIntegerOperands()
    {
        var (root, _) = Load("add", "1 + 2");
        var stmts = Body(root);
        Assert.Single(stmts.Body);
        var call = Assert.IsType<CallNode>(stmts.Body[0]);
        Assert.Equal("+", call.Name);
        var recv = Assert.IsType<IntegerNode>(call.Receiver);
        Assert.Equal(1L, recv.Value);
        var args = Assert.IsType<ArgumentsNode>(call.Arguments);
        var arg = Assert.IsType<IntegerNode>(args.Arguments[0]);
        Assert.Equal(2L, arg.Value);
    }

    [Fact]
    public void Def_IsDefNodeNamedFoo()
    {
        var (root, _) = Load("def_method", "def foo(a); a; end");
        var def = Assert.IsType<DefNode>(Body(root).Body[0]);
        Assert.Equal("foo", def.Name);
    }

    [Fact]
    public void StringInterpolation_IsInterpolatedStringNode()
    {
        var (root, _) = Load("str_interp", "\"a#{b}c\"");
        var interp = Assert.IsType<InterpolatedStringNode>(Body(root).Body[0]);
        // parts: "a", #{b}, "c"
        Assert.Equal(3, interp.Parts.Length);
        Assert.IsType<StringNode>(interp.Parts[0]);
        Assert.IsType<EmbeddedStatementsNode>(interp.Parts[1]);
        Assert.IsType<StringNode>(interp.Parts[2]);
    }

    [Fact]
    public void Class_IsClassNodeWithSuperclass()
    {
        var (root, _) = Load("klass", "class Foo < Bar; end");
        var cls = Assert.IsType<ClassNode>(Body(root).Body[0]);
        Assert.Equal("Foo", cls.Name);
        Assert.IsType<ConstantReadNode>(cls.Superclass);
    }

    [Fact]
    public void Bignum_IntegerNodeCarriesBigInteger()
    {
        var (root, _) = Load("bignum", "100000000000000000000");
        var i = Assert.IsType<IntegerNode>(Body(root).Body[0]);
        Assert.IsType<BigInteger>(i.Value);
        Assert.Equal(BigInteger.Parse("100000000000000000000"), (BigInteger)i.Value);
    }

    [Fact]
    public void Float_FloatNodeValue()
    {
        var (root, _) = Load("float_lit", "3.14");
        var f = Assert.IsType<FloatNode>(Body(root).Body[0]);
        Assert.Equal(3.14, f.Value, 10);
    }

    [Fact]
    public void Locations_PointIntoSource()
    {
        var (root, _) = Load("add", "1 + 2");
        var call = (CallNode)Body(root).Body[0];
        // the call spans the whole "1 + 2"
        Assert.Equal(0, call.Location.StartOffset);
        Assert.Equal(5, call.Location.Length);
        // the receiver "1" is at offset 0, length 1
        Assert.Equal(0, call.Receiver!.Location.StartOffset);
        Assert.Equal(1, call.Receiver.Location.Length);
    }
}
