#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates C# Prism AST node classes from Vendor/prism/config.yml (prism v1.8.1).
#
# Emits Src/SuperIronRuby/Parser/Nodes.g.cs:
#   - enum NodeType            (1-based, config file order = serialization type byte)
#   - [Flags] enum per group   (node-specific bits start at 1 << 2; bits 0-1 are
#                               the common newline/static flags)
#   - one sealed class per node with PascalCase typed fields, a full-field
#     constructor, and ChildNodes().
#
# The loader half (Loader.g.cs, per-node deserialization) is task P3; this script
# is structured with an emit_loader hook point so a second emitter slots in.
#
# Ground truth for serialization field order: the rendered serialize.rb for
# v1.8.1 at ~/.rbenv/.../prism/serialize.rb. Flag bit layout confirmed against
# prism/node.rb (e.g. CallNodeFlags::SAFE_NAVIGATION == 1 << 2).
#
# Deterministic: same config.yml in => byte-identical Nodes.g.cs out.

require "yaml"

ROOT = File.expand_path("..", __dir__)
CONFIG = File.join(ROOT, "Vendor", "prism", "config.yml")
OUT = File.join(ROOT, "Src", "SuperIronRuby", "Parser", "Nodes.g.cs")

config = YAML.load_file(CONFIG)
NODES = config.fetch("nodes")
FLAG_GROUPS = config.fetch("flags")

# snake_case (or PascalCase already) -> PascalCase
def pascal(name)
  name.split("_").map { |p| p.empty? ? "" : p[0].upcase + p[1..] }.join
end

# SCREAMING_SNAKE -> PascalCase (for flag value member names)
def flag_member(name)
  name.split("_").map { |p| p.empty? ? "" : p[0].upcase + p[1..].downcase }.join
end

# Map a config field type to (csharp_type, is_child_node, child_kind)
# child_kind: :single, :optional, :array, or nil
def map_type(type)
  case type
  when "node"        then ["Node",      :single]
  when "node?"       then ["Node?",     :optional]
  when "node[]"      then ["Node[]",    :array]
  when "location"    then ["Location",  nil]
  when "location?"   then ["Location?", nil]
  when "constant"    then ["string",    nil]
  when "constant?"   then ["string?",   nil]
  when "constant[]"  then ["string[]",  nil]
  when "string"      then ["string",    nil]
  when "uint8"       then ["int",       nil]
  when "uint32"      then ["int",       nil]
  when "integer"     then ["object",    nil] # long or System.Numerics.BigInteger
  when "double"      then ["double",    nil]
  else
    raise "unknown field type: #{type.inspect}"
  end
end

out = +""
out << "// <auto-generated />\n"
out << "// Generated by Tools/generate_nodes.rb from Vendor/prism/config.yml (prism v1.8.1).\n"
out << "// Do not edit by hand. Re-run: ruby Tools/generate_nodes.rb\n"
out << "#nullable enable\n"
out << "using System.Numerics;\n\n"
out << "namespace SuperIronRuby.Parser;\n\n"

# ---- NodeType enum ---------------------------------------------------------
out << "/// <summary>Prism node kind. Values are 1-based and match the\n"
out << "/// serialization type byte (config.yml node order).</summary>\n"
out << "public enum NodeType\n{\n"
NODES.each_with_index do |node, i|
  out << "    #{node["name"]} = #{i + 1},\n"
end
out << "}\n\n"

# ---- Flag enums ------------------------------------------------------------
FLAG_GROUPS.each do |group|
  values = group.fetch("values")
  out << "/// <summary>#{group["comment"]}</summary>\n" if group["comment"]
  out << "[System.Flags]\n"
  out << "public enum #{group["name"]}\n{\n"
  out << "    None = 0,\n"
  values.each_with_index do |v, i|
    # Node-specific flags start after the 2 reserved common bits.
    out << "    #{flag_member(v["name"])} = 1 << #{i + 2},\n"
  end
  out << "}\n\n"
end

# ---- Node classes ----------------------------------------------------------
NODES.each do |node|
  name = node["name"]
  fields = node["fields"] || []
  mapped = fields.map do |f|
    cs_type, child_kind = map_type(f["type"])
    { ruby: f["name"], cs: pascal(f["name"]), type: cs_type, child: child_kind }
  end

  out << "/// <summary>#{(node["comment"] || "").split("\n").first}</summary>\n"
  out << "public sealed class #{name} : Node\n{\n"
  out << "    public override NodeType Type => NodeType.#{name};\n\n"

  # Fields
  mapped.each do |f|
    out << "    public #{f[:type]} #{f[:cs]};\n"
  end

  # Typed flags accessor for nodes with a flag group
  if node["flags"]
    grp = node["flags"]
    out << "\n    /// <summary>Node-specific flags, typed.</summary>\n"
    out << "    public #{grp} FlagsTyped => (#{grp})Flags;\n"
  end

  # Constructor: (nodeId, location, flags, ...fields)
  ctor_params = ["uint nodeId", "Location location", "int flags"]
  mapped.each { |f| ctor_params << "#{f[:type]} #{f[:ruby]}" }
  out << "\n    public #{name}(#{ctor_params.join(", ")})\n    {\n"
  out << "        NodeId = nodeId;\n"
  out << "        Location = location;\n"
  out << "        Flags = flags;\n"
  mapped.each do |f|
    out << "        #{f[:cs]} = #{f[:ruby]};\n"
  end
  out << "    }\n"

  # ChildNodes()
  out << "\n    public override IEnumerable<Node?> ChildNodes()\n    {\n"
  child_fields = mapped.select { |f| f[:child] }
  if child_fields.empty?
    out << "        yield break;\n"
  else
    child_fields.each do |f|
      case f[:child]
      when :single, :optional
        out << "        yield return #{f[:cs]};\n"
      when :array
        out << "        foreach (var n in #{f[:cs]}) yield return n;\n"
      end
    end
  end
  out << "    }\n"

  out << "}\n\n"
end

File.write(OUT, out)
warn "generated #{OUT}: #{NODES.size} node classes, #{FLAG_GROUPS.size} flag enums"
